INSERT INTO ORGANIZATION (ID, NAME) VALUES (nextval('HIBERNATE_SEQUENCE'), 'Asociatia Romana a Bancilor');

WITH ouRow AS (
	INSERT INTO ORGANIZATIONENTITY (ORG_ENTITY_ID) VALUES (nextval('HIBERNATE_SEQUENCE'))
    RETURNING ORG_ENTITY_ID
) INSERT INTO ORGANIZATIONUNIT (ORG_ENTITY_ID, NAME, ORGANIZATION_ID) VALUES (
	(select ORG_ENTITY_ID from ouRow),
	'Presedinte Executiv',
	(select ID from ORGANIZATION where NAME = 'Asociatia Romana a Bancilor')
);

WITH ouRow AS (
	INSERT INTO ORGANIZATIONENTITY (ORG_ENTITY_ID) VALUES (nextval('HIBERNATE_SEQUENCE'))
    RETURNING ORG_ENTITY_ID
) INSERT INTO ORGANIZATIONUNIT (ORG_ENTITY_ID, NAME, PARENTOU_ORG_ENTITY_ID) VALUES (
	(select ORG_ENTITY_ID from ouRow),
	'Director Executiv(DEIC)',
	(select ORG_ENTITY_ID from ORGANIZATIONUNIT where NAME='Presedinte Executiv')
);
WITH ouRow AS (
	INSERT INTO ORGANIZATIONENTITY (ORG_ENTITY_ID) VALUES (nextval('HIBERNATE_SEQUENCE'))
    RETURNING ORG_ENTITY_ID
) INSERT INTO ORGANIZATIONUNIT (ORG_ENTITY_ID, NAME, PARENTOU_ORG_ENTITY_ID) VALUES (
	(select ORG_ENTITY_ID from ouRow),
	'Departament Resurse Umane',
	(select ORG_ENTITY_ID from ORGANIZATIONUNIT where NAME='Director Executiv(DEIC)')
);
WITH ouRow AS (
	INSERT INTO ORGANIZATIONENTITY (ORG_ENTITY_ID) VALUES (nextval('HIBERNATE_SEQUENCE'))
    RETURNING ORG_ENTITY_ID
) INSERT INTO ORGANIZATIONUNIT (ORG_ENTITY_ID, NAME, PARENTOU_ORG_ENTITY_ID) VALUES (
	(select ORG_ENTITY_ID from ouRow),
	'Departament Contabilitate',
	(select ORG_ENTITY_ID from ORGANIZATIONUNIT where NAME='Director Executiv(DEIC)')
);
WITH ouRow AS (
	INSERT INTO ORGANIZATIONENTITY (ORG_ENTITY_ID) VALUES (nextval('HIBERNATE_SEQUENCE'))
    RETURNING ORG_ENTITY_ID
) INSERT INTO ORGANIZATIONUNIT (ORG_ENTITY_ID, NAME, PARENTOU_ORG_ENTITY_ID) VALUES (
	(select ORG_ENTITY_ID from ouRow),
	'Departament Administrativ',
	(select ORG_ENTITY_ID from ORGANIZATIONUNIT where NAME='Director Executiv(DEIC)')
);

WITH ouRow AS (
	INSERT INTO ORGANIZATIONENTITY (ORG_ENTITY_ID) VALUES (nextval('HIBERNATE_SEQUENCE'))
    RETURNING ORG_ENTITY_ID
) INSERT INTO ORGANIZATIONUNIT (ORG_ENTITY_ID, NAME, PARENTOU_ORG_ENTITY_ID) VALUES (
	(select ORG_ENTITY_ID from ouRow),
	'Director Executiv Proiecte(DEPR)',
	(select ORG_ENTITY_ID from ORGANIZATIONUNIT where NAME='Presedinte Executiv')
);
WITH ouRow AS (
	INSERT INTO ORGANIZATIONENTITY (ORG_ENTITY_ID) VALUES (nextval('HIBERNATE_SEQUENCE'))
    RETURNING ORG_ENTITY_ID
) INSERT INTO ORGANIZATIONUNIT (ORG_ENTITY_ID, NAME, PARENTOU_ORG_ENTITY_ID) VALUES (
	(select ORG_ENTITY_ID from ouRow),
	'Departament Informatica',
	(select ORG_ENTITY_ID from ORGANIZATIONUNIT where NAME='Director Executiv Proiecte(DEPR)')
);
WITH ouRow AS (
	INSERT INTO ORGANIZATIONENTITY (ORG_ENTITY_ID) VALUES (nextval('HIBERNATE_SEQUENCE'))
    RETURNING ORG_ENTITY_ID
) INSERT INTO ORGANIZATIONUNIT (ORG_ENTITY_ID, NAME, PARENTOU_ORG_ENTITY_ID) VALUES (
	(select ORG_ENTITY_ID from ouRow),
	'Departament Asistenta',
	(select ORG_ENTITY_ID from ORGANIZATIONUNIT where NAME='Director Executiv Proiecte(DEPR)')
);

WITH ouRow AS (
	INSERT INTO ORGANIZATIONENTITY (ORG_ENTITY_ID) VALUES (nextval('HIBERNATE_SEQUENCE'))
    RETURNING ORG_ENTITY_ID
) INSERT INTO ORGANIZATIONUNIT (ORG_ENTITY_ID, NAME, PARENTOU_ORG_ENTITY_ID) VALUES (
	(select ORG_ENTITY_ID from ouRow),
	'Director Executiv Operatiuni Plati(DEOP)',
	(select ORG_ENTITY_ID from ORGANIZATIONUNIT where NAME='Presedinte Executiv')
);
WITH ouRow AS (
	INSERT INTO ORGANIZATIONENTITY (ORG_ENTITY_ID) VALUES (nextval('HIBERNATE_SEQUENCE'))
    RETURNING ORG_ENTITY_ID
) INSERT INTO ORGANIZATIONUNIT (ORG_ENTITY_ID, NAME, PARENTOU_ORG_ENTITY_ID) VALUES (
	(select ORG_ENTITY_ID from ouRow),
	'Departament Financiar Bancar',
	(select ORG_ENTITY_ID from ORGANIZATIONUNIT where NAME='Director Executiv Operatiuni Plati(DEOP)')
);
WITH ouRow AS (
	INSERT INTO ORGANIZATIONENTITY (ORG_ENTITY_ID) VALUES (nextval('HIBERNATE_SEQUENCE'))
    RETURNING ORG_ENTITY_ID
) INSERT INTO ORGANIZATIONUNIT (ORG_ENTITY_ID, NAME, PARENTOU_ORG_ENTITY_ID) VALUES (
	(select ORG_ENTITY_ID from ouRow),
	'Departament Asistent Manager',
	(select ORG_ENTITY_ID from ORGANIZATIONUNIT where NAME='Director Executiv Operatiuni Plati(DEOP)')
);
WITH ouRow AS (
	INSERT INTO ORGANIZATIONENTITY (ORG_ENTITY_ID) VALUES (nextval('HIBERNATE_SEQUENCE'))
    RETURNING ORG_ENTITY_ID
) INSERT INTO ORGANIZATIONUNIT (ORG_ENTITY_ID, NAME, PARENTOU_ORG_ENTITY_ID) VALUES (
	(select ORG_ENTITY_ID from ouRow),
	'Departament Juridic',
	(select ORG_ENTITY_ID from ORGANIZATIONUNIT where NAME='Director Executiv Operatiuni Plati(DEOP)')
);
WITH ouRow AS (
	INSERT INTO ORGANIZATIONENTITY (ORG_ENTITY_ID) VALUES (nextval('HIBERNATE_SEQUENCE'))
    RETURNING ORG_ENTITY_ID
) INSERT INTO ORGANIZATIONUNIT (ORG_ENTITY_ID, NAME, PARENTOU_ORG_ENTITY_ID) VALUES (
	(select ORG_ENTITY_ID from ouRow),
	'Departament Scheme Plati',
	(select ORG_ENTITY_ID from ORGANIZATIONUNIT where NAME='Director Executiv Operatiuni Plati(DEOP)')
);

WITH ouRow AS (
	INSERT INTO ORGANIZATIONENTITY (ORG_ENTITY_ID) VALUES (nextval('HIBERNATE_SEQUENCE'))
    RETURNING ORG_ENTITY_ID
) INSERT INTO ORGANIZATIONUNIT (ORG_ENTITY_ID, NAME, ORGANIZATION_ID) VALUES (
	(select ORG_ENTITY_ID from ouRow),
	'Conturi dezactivate',
	(select ID from ORGANIZATION where NAME = 'Asociatia Romana a Bancilor')
);