package ro.cloudSoft.cloudDoc.core.constants;

public interface ParameterConstants {
	public static String PARAM_NAME_PROIECT_GRAD_REALIZARE_PONDERE_IN_PROCENTE_PENTRU_NR_ACTIUNI_REALIZATE_PE_NR_ACTIUNI_ESTIMATE = "proiect.grad_realizare_pondere_in_procente_pentru_nr_actiuni_realizate_pe_nr_actiuni_estimate";
	public static String PARAM_NAME_PROIECT_GRAD_REALIZARE_PONDERE_IN_PROCENTE_PENTRU_REALIZARE_ACTIUNI_IN_TERMEN = "proiect.grad_realizare_pondere_in_procente_pentru_realizare_actiuni_in_termen";
	public static String PARAM_NAME_PROIECT_GRAD_REALIZARE_PONDERE_IN_PROCENTE_PENTRU_ESTIMARE_RESPONSABIL = "proiect.grad_realizare_pondere_in_procente_pentru_estimare_responsabil";
	
	public static String PARAM_NAME_PROIECT_GRAD_REALIZARE_PONDERE_IN_PROCENTE_PENTRU_PROIECTELE_CU_GRAD_DE_IMPORTANTA_CRITIC = "proiect.grad_realizare_pondere_in_procente_pentru_proiectele_cu_grad_de_importanta_critic";
	public static String PARAM_NAME_PROIECT_GRAD_REALIZARE_PONDERE_IN_PROCENTE_PENTRU_PROIECTELE_CU_GRAD_DE_IMPORTANTA_IMPORTANT = "proiect.grad_realizare_pondere_in_procente_pentru_proiectele_cu_grad_de_importanta_important";
	public static String PARAM_NAME_PROIECT_GRAD_REALIZARE_PONDERE_IN_PROCENTE_PENTRU_PROIECTELE_CU_GRAD_DE_IMPORTANTA_IN_ASTEPTARE = "proiect.grad_realizare_pondere_in_procente_pentru_proiectele_cu_grad_de_importanta_in_asteptare";
	public static String PARAM_NAME_PROIECT_GRAD_REALIZARE_PONDERE_IN_PROCENTE_PENTRU_PROIECTELE_CU_GRAD_DE_IMPORTANTA_STRATEGIC = "proiect.grad_realizare_pondere_in_procente_pentru_proiectele_cu_grad_de_importanta_strategic";
	
	public static String PARAM_NAME_COMISIE_GL_NR_ANI_VALABILITATE_MANDAT_PRESEDINTE_VICEPRESEDINTE = "comisie_gl.numar_ani_valabilitate_mandat_presedinte_vicepresedinte";
	public static String PARAM_NAME_COMISIE_GL_NR_ANI_VALABILITATE_MANDAT_MEMBRU_CD_COORDONATOR = "comisie_gl.numar_ani_valabilitate_mandat_membru_cd_coordonator";	
	
	public static String PARAM_NAME_RAPORT_COEFICIENT_PUNCTAJ_MAXIM = "raport.coeficient.punctaj_maxim";
	public static String PARAM_NAME_RAPORT_COEFICIENT_PROCENTUAL_LEVEL_0 = "raport.coeficient_procentual.level_0";
	public static String PARAM_NAME_RAPORT_COEFICIENT_PROCENTUAL_LEVEL_1 = "raport.coeficient_procentual.level_1";
	public static String PARAM_NAME_RAPORT_COEFICIENT_PROCENTUAL_LEVEL_2 = "raport.coeficient_procentual.level_2";
	public static String PARAM_NAME_RAPORT_COEFICIENT_PROCENTUAL_LEVEL_3 = "raport.coeficient_procentual.level_3";
	public static String PARAM_NAME_RAPORT_COEFICIENT_PROCENTUAL_LEVEL_3_PLUS = "raport.coeficient_procentual.level_3_plus";
	public static String PARAM_NAME_RAPORT_COEFICIENT_PROCENTUAL_IN_AFARA_NOMNINALIZARILOR = "raport.coeficient_procentual.in_afara_nominalizarilor";
	public static String PARAM_NAME_RAPORT_COEFICIENT_PROCENTUAL_GRAD_NR_RASPUNSURI = "raport.coeficient_procentual.grad_nr_raspunsuri";
	public static String PARAM_NAME_RAPORT_COEFICIENT_PROCENTUAL_RASPUNSURI_CU_PROPUNERI_ARGUMENTARI = "raport.coeficient_procentual.raspunsuri_cu_propuneri_argumentari";
	public static String PARAM_NAME_RAPORT_COEFICIENT_PROCENTUAL_RASPUNSURI_FARA_PROPUNERI_ARGUMENTARI = "raport.coeficient_procentual.raspunsuri_fara_propuneri_argumentari";
	public static String PARAM_NAME_RAPORT_COEFICIENT_PROCENTUAL_RASPUNSURI_FARA_INTARZIERE = "raport.coeficient_procentual.raspunsuri_fara_intarziere";
	public static String PARAM_NAME_RAPORT_COEFICIENT_PROCENTUAL_RASPUNSURI_CU_INTARZIERE_PESTE_O_ZI = "raport.coeficient_procentual.raspunsuri_cu_intarziere_peste_o_zi";
	public static String PARAM_NAME_RAPORT_COEFICIENT_PROCENTUAL_PREZENTE = "raport.coeficient_procentual.prezente";
	public static String PARAM_NAME_RAPORT_COEFICIENT_PROCENTUAL_RASPUNSURI = "raport.coeficient_procentual.raspunsuri";
	public static String PARAM_NAME_RAPORT_COEFICIENT_PROCENTUAL_CALITATE_RASPUNSURI = "raport.coeficient_procentual.calitate_raspunsuri";
	public static String PARAM_NAME_RAPORT_COEFICIENT_PROCENTUAL_VITEZA_RASPUNSURI = "raport.coeficient_procentual.viteza_raspunsuri";
	
	public static String PARAM_NAME_RAPORT_COEFICIENT_PROCENTUAL_NOTA_PREZENTA_NUMAR = "raport.coeficient_procentual.nota_prezenta_numar";
	public static String PARAM_NAME_RAPORT_COEFICIENT_PROCENTUAL_NOTA_PREZENTA_STRUCTURA = "raport.coeficient_procentual.nota_prezenta_structura";
	public static String PARAM_NAME_RAPORT_COEFICIENT_PROCENTUAL_NUMAR_SEDINTE_PONDERAT = "raport.coeficient.numar_sedinte_ponderat";
	public static String PARAM_NAME_RAPORT_COEFICIENT_PROCENTUAL_NOTA_NUMAR_RASPUNSURI = "raport.coeficient_procentual.nota_numar_raspunsuri";
	public static String PARAM_NAME_RAPORT_COEFICIENT_PROCENTUAL_NUMAR_RASPUNSURI_FARA_PROPUNERI_PE_BANCA_RESPECTIVA = "raport.coeficient_procentual.numar_raspunsuri_fara_propuneri_pe_banca_respectiva";
	public static String PARAM_NAME_RAPORT_COEFICIENT_PROCENTUAL_NUMAR_RASPUNSURI_CU_PROPUNERI_PE_BANCA_RESPECTIVA = "raport.coeficient_procentual.numar_raspunsuri_cu_propuneri_pe_banca_respectiva";
	public static String PARAM_NAME_RAPORT_COEFICIENT_PROCENTUAL_NUMAR_RASPUNSURI_FARA_INTARZIERI_PE_BANCA_RESPECTIVA = "raport.coeficient_procentual.numar_raspunsuri_fara_intarzieri_pe_banca_respectiva";
	public static String PARAM_NAME_RAPORT_COEFICIENT_PROCENTUAL_NUMAR_RASPUNSURI_CU_INTARZIERI_PE_BANCA_RESPECTIVA = "raport.coeficient_procentual.numar_raspunsuri_cu_intarzieri_pe_banca_respectiva";

	public static String PARAM_NAME_RAPORT_COEFICIENT_PROCENTUAL_NOTA_RASPUNSURI_AJUSTATA_CU_VITEZA_RASPUNS = "raport.coeficient_procentual.nota_raspunsuri_ajustata_cu_viteza_raspuns";
	public static String PARAM_NAME_RAPORT_COEFICIENT_PROCENTUAL_NOTA_RASPUNSURI_AJUSTATA_CALITATE_RASPUNS = "raport.coeficient_procentual.nota_raspunsuri_ajustata_cu_calitate_raspuns";
	

	public static String PARAM_NAME_RAPORT_COEFICIENT_PROCENTUAL_NOTA_FINALA_PREZENTA = "raport.coeficient_procentual.nota_finala_prezenta";
	public static String PARAM_NAME_RAPORT_COEFICIENT_PROCENTUAL_NOTA_TOTALA_RASPUNSURI_BANCI = "raport.coeficient_procentual.nota_totala_raspunsuri_banci";
	
	public static String PARAM_NAME_RAPORT_COEFICIENT_NUMAR_TOTAL_INTEROGARI_ARB = "raport.coeficient.numar_total_interogari_arb";
	
	public static String PARAM_NAME_NOTIFICARI_EMAIL_NR_ORGANISME_BUGETATE_DATA_INCEPUT = "notificari.email.nr_organisme_bugetate.data_inceput";
	public static String PARAM_NAME_NOTIFICARI_EMAIL_NR_ORGANISME_BUGETATE_SUBIECT = "notificari.email.nr_organisme_bugetate.subiect";
	public static String PARAM_NAME_NOTIFICARI_EMAIL_NR_ORGANISME_BUGETATE_CONTINUT = "notificari.email.nr_organisme_bugetate.continut";
	public static String PARAM_NAME_NOTIFICARI_EMAIL_SEDINTA_AGA_SUBIECT = "notificari.email.sedinta_aga.subiect";
	public static String PARAM_NAME_NOTIFICARI_EMAIL_SEDINTA_AGA_CONTINUT = "notificari.email.sedinta_aga.continut";
	public static String PARAM_NAME_NOTIFICARI_EMAIL_EXPIRARE_MANDAT_REPREZENTANTI_COMISIE_GL_SUBIECT = "notificari.email.expirare_mandat_reprezentanti_comisie_gl.subiect";
	public static String PARAM_NAME_NOTIFICARI_EMAIL_EXPIRARE_MANDAT_REPREZENTANTI_COMISIE_GL_CONTINUT = "notificari.email.expirare_mandat_reprezentanti_comisie_gl.continut";
	
	public static String PARAM_NAME_DOCUMENT_NR_DE_ANI_PANA_LA_ARHIVARE = "document.nr_de_ani_pana_la_arhivare";
	
	public static String PARAM_PROIECT_NUMAR_ZILE_PANA_LA_EXPIRARE = "proiect.notificare_expirare_proiect.numar_zile_inainte";
}