-- nomenclator
INSERT INTO NOMENCLATOR (ID, NAME, CODE) VALUES (HIBERNATE_SEQUENCE.nextval, 'Institutii', 'institutii');

-- atributes
INSERT INTO NOMENCLATOR_ATTRIBUTE (ID, NOMENCLATOR_ID, NAME, KEY, COLUMN_NAME, TYPE,TYPE_NOMENCLATOR_ID, UI_ORDER, REQUIRED) 
    VALUES (HIBERNATE_SEQUENCE.nextval, (select ID from nomenclator where name='Institutii'),	'Tip Institutie', 'attribute1', 'ATTRIBUTE1', 'NOMENCLATOR', (select ID from nomenclator where name='Tip Institutii'), 1, 1);  
INSERT INTO NOMENCLATOR_ATTRIBUTE (ID, NOMENCLATOR_ID, NAME, KEY, COLUMN_NAME, TYPE,TYPE_NOMENCLATOR_ID, UI_ORDER, REQUIRED) 
    VALUES (HIBERNATE_SEQUENCE.nextval, (select ID from nomenclator where name='Institutii'),	'Denumire institutie', 'attribute2', 'ATTRIBUTE2', 'TEXT', NULL, 2, 1);  
INSERT INTO NOMENCLATOR_ATTRIBUTE (ID, NOMENCLATOR_ID, NAME, KEY, COLUMN_NAME, TYPE,TYPE_NOMENCLATOR_ID, UI_ORDER, REQUIRED)  
    VALUES (HIBERNATE_SEQUENCE.nextval, (select ID from nomenclator where name='Institutii'),	'Abreviere', 'attribute3', 'ATTRIBUTE3', 'TEXT', NULL, 3, 0);  
INSERT INTO NOMENCLATOR_ATTRIBUTE (ID, NOMENCLATOR_ID, NAME, KEY, COLUMN_NAME, TYPE,TYPE_NOMENCLATOR_ID, UI_ORDER, REQUIRED)  
    VALUES (HIBERNATE_SEQUENCE.nextval, (select ID from nomenclator where name='Institutii'),	'Cod BIC', 'attribute4', 'ATTRIBUTE4', 'TEXT', NULL, 4, 0);  
INSERT INTO NOMENCLATOR_ATTRIBUTE (ID, NOMENCLATOR_ID, NAME, KEY, COLUMN_NAME, TYPE,TYPE_NOMENCLATOR_ID, UI_ORDER, REQUIRED) 
    VALUES (HIBERNATE_SEQUENCE.nextval, (select ID from nomenclator where name='Institutii'),	'Cod Unic de Inregistrare', 'attribute5', 'ATTRIBUTE5', 'TEXT', NULL, 5, 0);  
INSERT INTO NOMENCLATOR_ATTRIBUTE (ID, NOMENCLATOR_ID, NAME, KEY, COLUMN_NAME, TYPE,TYPE_NOMENCLATOR_ID, UI_ORDER, REQUIRED) 
    VALUES (HIBERNATE_SEQUENCE.nextval, (select ID from nomenclator where name='Institutii'),	'Adresa', 'attribute6', 'ATTRIBUTE6', 'TEXT', NULL, 6, 0);  
INSERT INTO NOMENCLATOR_ATTRIBUTE (ID, NOMENCLATOR_ID, NAME, KEY, COLUMN_NAME, TYPE,TYPE_NOMENCLATOR_ID, UI_ORDER, REQUIRED) 
    VALUES (HIBERNATE_SEQUENCE.nextval, (select ID from nomenclator where name='Institutii'),	'Oras', 'attribute7', 'ATTRIBUTE7', 'TEXT', NULL, 7, 0);  
INSERT INTO NOMENCLATOR_ATTRIBUTE (ID, NOMENCLATOR_ID, NAME, KEY, COLUMN_NAME, TYPE,TYPE_NOMENCLATOR_ID, UI_ORDER, REQUIRED) 
    VALUES (HIBERNATE_SEQUENCE.nextval, (select ID from nomenclator where name='Institutii'),	'Site web', 'attribute8', 'ATTRIBUTE8', 'TEXT', NULL, 8, 0);  
INSERT INTO NOMENCLATOR_ATTRIBUTE (ID, NOMENCLATOR_ID, NAME, KEY, COLUMN_NAME, TYPE,TYPE_NOMENCLATOR_ID, UI_ORDER, REQUIRED) 
    VALUES (HIBERNATE_SEQUENCE.nextval, (select ID from nomenclator where name='Institutii'),	'Telefon', 'attribute9', 'ATTRIBUTE9', 'TEXT', NULL, 9, 0);  
INSERT INTO NOMENCLATOR_ATTRIBUTE (ID, NOMENCLATOR_ID, NAME, KEY, COLUMN_NAME, TYPE,TYPE_NOMENCLATOR_ID, UI_ORDER, REQUIRED) 
    VALUES (HIBERNATE_SEQUENCE.nextval, (select ID from nomenclator where name='Institutii'),	'Email', 'attribute10', 'ATTRIBUTE10', 'TEXT', NULL, 10, 0);  
INSERT INTO NOMENCLATOR_ATTRIBUTE (ID, NOMENCLATOR_ID, NAME, KEY, COLUMN_NAME, TYPE,TYPE_NOMENCLATOR_ID, UI_ORDER, REQUIRED) 
    VALUES (HIBERNATE_SEQUENCE.nextval, (select ID from nomenclator where name='Institutii'),	'Fax', 'attribute11', 'ATTRIBUTE11', 'TEXT', NULL, 11, 0);  
INSERT INTO NOMENCLATOR_ATTRIBUTE (ID, NOMENCLATOR_ID, NAME, KEY, COLUMN_NAME, TYPE,TYPE_NOMENCLATOR_ID, UI_ORDER, REQUIRED) 
    VALUES (HIBERNATE_SEQUENCE.nextval, (select ID from nomenclator where name='Institutii'),	'Numarul de ordine Registrul Comertului', 'attribute12', 'ATTRIBUTE12', 'TEXT', NULL, 12, 0);  
INSERT INTO NOMENCLATOR_ATTRIBUTE (ID, NOMENCLATOR_ID, NAME, KEY, COLUMN_NAME, TYPE,TYPE_NOMENCLATOR_ID, UI_ORDER, REQUIRED) 
    VALUES (HIBERNATE_SEQUENCE.nextval, (select ID from nomenclator where name='Institutii'),	'Radiat', 'attribute13', 'ATTRIBUTE13', 'BOOLEAN', NULL, 13, 0);  
INSERT INTO NOMENCLATOR_ATTRIBUTE (ID, NOMENCLATOR_ID, NAME, KEY, COLUMN_NAME, TYPE,TYPE_NOMENCLATOR_ID, UI_ORDER, REQUIRED) 
    VALUES (HIBERNATE_SEQUENCE.nextval, (select ID from nomenclator where name='Institutii'),	'Data radierii', 'attribute14', 'ATTRIBUTE14', 'TEXT', NULL, 14, 0);  
INSERT INTO NOMENCLATOR_ATTRIBUTE (ID, NOMENCLATOR_ID, NAME, KEY, COLUMN_NAME, TYPE,TYPE_NOMENCLATOR_ID, UI_ORDER, REQUIRED) 
    VALUES (HIBERNATE_SEQUENCE.nextval, (select ID from nomenclator where name='Institutii'),	'Numar PV la Notariat', 'attribute15', 'ATTRIBUTE15', 'TEXT', NULL, 15, 0);  
INSERT INTO NOMENCLATOR_ATTRIBUTE (ID, NOMENCLATOR_ID, NAME, KEY, COLUMN_NAME, TYPE,TYPE_NOMENCLATOR_ID, UI_ORDER, REQUIRED)  
    VALUES (HIBERNATE_SEQUENCE.nextval, (select ID from nomenclator where name='Institutii'),	'Data PV la notariat', 'attribute16', 'ATTRIBUTE16', 'DATE', NULL, 16, 0);  
INSERT INTO NOMENCLATOR_ATTRIBUTE (ID, NOMENCLATOR_ID, NAME, KEY, COLUMN_NAME, TYPE,TYPE_NOMENCLATOR_ID, UI_ORDER, REQUIRED)  
    VALUES (HIBERNATE_SEQUENCE.nextval, (select ID from nomenclator where name='Institutii'),	'Numar incheiere la Judecatorie', 'attribute17', 'ATTRIBUTE17', 'TEXT', NULL, 17, 0);  
INSERT INTO NOMENCLATOR_ATTRIBUTE (ID, NOMENCLATOR_ID, NAME, KEY, COLUMN_NAME, TYPE,TYPE_NOMENCLATOR_ID, UI_ORDER, REQUIRED)  
    VALUES (HIBERNATE_SEQUENCE.nextval, (select ID from nomenclator where name='Institutii'),	'Data incheierii la Judecatorie', 'attribute18', 'ATTRIBUTE18', 'DATE', NULL, 18, 0);  
INSERT INTO NOMENCLATOR_ATTRIBUTE (ID, NOMENCLATOR_ID, NAME, KEY, COLUMN_NAME, TYPE,TYPE_NOMENCLATOR_ID, UI_ORDER, REQUIRED)  
    VALUES (HIBERNATE_SEQUENCE.nextval, (select ID from nomenclator where name='Institutii'),	'Presedinte DG', 'attribute19', 'ATTRIBUTE19', 'TEXT', NULL, 19, 0);  
INSERT INTO NOMENCLATOR_ATTRIBUTE (ID, NOMENCLATOR_ID, NAME, KEY, COLUMN_NAME, TYPE,TYPE_NOMENCLATOR_ID, UI_ORDER, REQUIRED) 
    VALUES (HIBERNATE_SEQUENCE.nextval, (select ID from nomenclator where name='Institutii'),	'Vicepresedinte DG Adj', 'attribute20', 'ATTRIBUTE20', 'TEXT', NULL, 20, 0);  
INSERT INTO NOMENCLATOR_ATTRIBUTE (ID, NOMENCLATOR_ID, NAME, KEY, COLUMN_NAME, TYPE,TYPE_NOMENCLATOR_ID, UI_ORDER, REQUIRED) 
    VALUES (HIBERNATE_SEQUENCE.nextval, (select ID from nomenclator where name='Institutii'),	'Data aprobarii cererii de aderare la ARB', 'attribute21', 'ATTRIBUTE21', 'DATE', NULL, 21, 0);  
INSERT INTO NOMENCLATOR_ATTRIBUTE (ID, NOMENCLATOR_ID, NAME, KEY, COLUMN_NAME, TYPE,TYPE_NOMENCLATOR_ID, UI_ORDER, REQUIRED) 
    VALUES (HIBERNATE_SEQUENCE.nextval, (select ID from nomenclator where name='Institutii'),	'Nume reprezentant membru afiliat', 'attribute22', 'ATTRIBUTE22', 'TEXT', NULL, 22, 0);  
INSERT INTO NOMENCLATOR_ATTRIBUTE (ID, NOMENCLATOR_ID, NAME, KEY, COLUMN_NAME, TYPE,TYPE_NOMENCLATOR_ID, UI_ORDER, REQUIRED) 
    VALUES (HIBERNATE_SEQUENCE.nextval, (select ID from nomenclator where name='Institutii'),	'Prenume reprezentant membru afiliat', 'attribute23', 'ATTRIBUTE23', 'TEXT', NULL, 23, 0);  
INSERT INTO NOMENCLATOR_ATTRIBUTE (ID, NOMENCLATOR_ID, NAME, KEY, COLUMN_NAME, TYPE,TYPE_NOMENCLATOR_ID, UI_ORDER, REQUIRED) 
    VALUES (HIBERNATE_SEQUENCE.nextval, (select ID from nomenclator where name='Institutii'),	'Functie reprezentant membru afiliat', 'attribute24', 'ATTRIBUTE24', 'TEXT', NULL, 24, 0);  
INSERT INTO NOMENCLATOR_ATTRIBUTE (ID, NOMENCLATOR_ID, NAME, KEY, COLUMN_NAME, TYPE,TYPE_NOMENCLATOR_ID, UI_ORDER, REQUIRED)  
    VALUES (HIBERNATE_SEQUENCE.nextval, (select ID from nomenclator where name='Institutii'),	'Observatii', 'attribute25', 'ATTRIBUTE25', 'TEXT', NULL, 25, 0);  

--ui attributes
INSERT INTO NOMENCLATOR_UI_ATTRIBUTE (
	ID, 
	NOMENCLATOR_ID, 
	ATTRIBUTE_ID, 
	UI_ORDER
) VALUES (
	HIBERNATE_SEQUENCE.nextval, 
	(select ID from NOMENCLATOR where NAME='Institutii'),
	(select ID from NOMENCLATOR_ATTRIBUTE where NOMENCLATOR_ID=(select ID from NOMENCLATOR where NAME='Institutii') and KEY='attribute2'),
	1
);

-- valori
INSERT INTO NOMENCLATOR_VALUES (ID, NOMENCLATOR_ID, ATTRIBUTE1, ATTRIBUTE2, ATTRIBUTE3, ATTRIBUTE4, ATTRIBUTE5, ATTRIBUTE6,ATTRIBUTE7, ATTRIBUTE8, ATTRIBUTE9, ATTRIBUTE10, ATTRIBUTE11, ATTRIBUTE12, ATTRIBUTE13, ATTRIBUTE14, ATTRIBUTE15, ATTRIBUTE16, ATTRIBUTE17, ATTRIBUTE18, ATTRIBUTE19, ATTRIBUTE20, ATTRIBUTE21, ATTRIBUTE22, ATTRIBUTE23, ATTRIBUTE24, ATTRIBUTE25, DELETED) 
    VALUES (HIBERNATE_SEQUENCE.nextval, (select ID from nomenclator where name='Institutii'), (SELECT ID FROM NOMENCLATOR_VALUES WHERE NOMENCLATOR_ID=(select ID from nomenclator where name='Tip Institutii') and  ATTRIBUTE1 = 'Membru ARB (B)'), 'Institutie 1', 'I1','545', '464644', 'Iuliu Maniu 23', 'Alba Iulia', 'https://ro.lipsum.com/', '0740685897', 'activitiorga@gmail.com', '0285369874','J01/2016', 'false', NULL, '4232', '2017.03.02', '34534','2017.03.20','Ionescu Pavel', 'Popa Amalia', NULL, NULL, NULL, NULL, 'Observatie membru arb 1', 0);
	
INSERT INTO NOMENCLATOR_VALUES (ID, NOMENCLATOR_ID, ATTRIBUTE1, ATTRIBUTE2, ATTRIBUTE3, ATTRIBUTE4, ATTRIBUTE5, ATTRIBUTE6,ATTRIBUTE7, ATTRIBUTE8, ATTRIBUTE9, ATTRIBUTE10, ATTRIBUTE11, ATTRIBUTE12, ATTRIBUTE13, ATTRIBUTE14, ATTRIBUTE15, ATTRIBUTE16, ATTRIBUTE17, ATTRIBUTE18, ATTRIBUTE19, ATTRIBUTE20, ATTRIBUTE21, ATTRIBUTE22, ATTRIBUTE23, ATTRIBUTE24, ATTRIBUTE25, DELETED) 
    VALUES (HIBERNATE_SEQUENCE.nextval, (select ID from nomenclator where name='Institutii'), (SELECT ID FROM NOMENCLATOR_VALUES WHERE NOMENCLATOR_ID=(select ID from nomenclator where name='Tip Institutii') and  ATTRIBUTE1 = 'Membru ARB (B)'), 'Institutie 2', 'I2','435', '765876', 'Motilor 23', 'Alba Iulia', 'https://ro.lipsum.com/', '0745685877', 'activitiorga@mail.com', '0285369823','J01/2017', 'true', '2018.03.20', '7656', '2016.03.03', '765','2016.03.20','Florea Pavel', 'Popa Valentin', NULL, NULL, NULL, NULL, 'Observatie membru arb 2', 0);
   
INSERT INTO NOMENCLATOR_VALUES (ID, NOMENCLATOR_ID, ATTRIBUTE1, ATTRIBUTE2, ATTRIBUTE3, ATTRIBUTE4, ATTRIBUTE5, ATTRIBUTE6,ATTRIBUTE7, ATTRIBUTE8, ATTRIBUTE9, ATTRIBUTE10, ATTRIBUTE11, ATTRIBUTE12, ATTRIBUTE13, ATTRIBUTE14, ATTRIBUTE15, ATTRIBUTE16, ATTRIBUTE17, ATTRIBUTE18, ATTRIBUTE19, ATTRIBUTE20, ATTRIBUTE21, ATTRIBUTE22, ATTRIBUTE23, ATTRIBUTE24, ATTRIBUTE25, DELETED) 
    VALUES (HIBERNATE_SEQUENCE.nextval, (select ID from nomenclator where name='Institutii'), (SELECT ID FROM NOMENCLATOR_VALUES WHERE NOMENCLATOR_ID=(select ID from nomenclator where name='Tip Institutii') and  ATTRIBUTE1 = 'Membru Afiliat (A)'), 'Institutie 3', 'I3','8686', '757867', 'Revolutiei 53', 'Alba Iulia', 'https://ro.lipsum.com/', '0740685822', 'activitiorga@gmail.com', '0285369824','J01/2015', 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2017.04.10', 'Coman', 'Aurel', 'Contabil', 'Observatie membru afiliat 1', 0);
	
INSERT INTO NOMENCLATOR_VALUES (ID, NOMENCLATOR_ID, ATTRIBUTE1, ATTRIBUTE2, ATTRIBUTE3, ATTRIBUTE4, ATTRIBUTE5, ATTRIBUTE6,ATTRIBUTE7, ATTRIBUTE8, ATTRIBUTE9, ATTRIBUTE10, ATTRIBUTE11, ATTRIBUTE12, ATTRIBUTE13, ATTRIBUTE14, ATTRIBUTE15, ATTRIBUTE16, ATTRIBUTE17, ATTRIBUTE18, ATTRIBUTE19, ATTRIBUTE20, ATTRIBUTE21, ATTRIBUTE22, ATTRIBUTE23, ATTRIBUTE24, ATTRIBUTE25, DELETED) 
    VALUES (HIBERNATE_SEQUENCE.nextval, (select ID from nomenclator where name='Institutii'), (SELECT ID FROM NOMENCLATOR_VALUES WHERE NOMENCLATOR_ID=(select ID from nomenclator where name='Tip Institutii') and  ATTRIBUTE1 = 'Membru Afiliat (A)'), 'Institutie 4', 'I4','57554', '744778', 'Motilor 63', 'Alba Iulia', 'https://ro.lipsum.com/', '0745685834', 'activitiorga@mail.com', '0285369889','J01/2014', 'true', '2017.02.20', NULL, NULL, NULL, NULL, NULL, NULL, '2016.04.10', 'Cornea', 'Flaviu', 'Sef Contabil', 'Observatie membru afiliat 2', 0);

INSERT INTO NOMENCLATOR_VALUES (ID, NOMENCLATOR_ID, ATTRIBUTE1, ATTRIBUTE2, ATTRIBUTE3, ATTRIBUTE4, ATTRIBUTE5, ATTRIBUTE6,ATTRIBUTE7, ATTRIBUTE8, ATTRIBUTE9, ATTRIBUTE10, ATTRIBUTE11, ATTRIBUTE12, ATTRIBUTE13, ATTRIBUTE14, ATTRIBUTE15, ATTRIBUTE16, ATTRIBUTE17, ATTRIBUTE18, ATTRIBUTE19, ATTRIBUTE20, ATTRIBUTE21, ATTRIBUTE22, ATTRIBUTE23, ATTRIBUTE24, ATTRIBUTE25, DELETED) 
    VALUES (HIBERNATE_SEQUENCE.nextval, (select ID from nomenclator where name='Institutii'), (SELECT ID FROM NOMENCLATOR_VALUES WHERE NOMENCLATOR_ID=(select ID from nomenclator where name='Tip Institutii') and  ATTRIBUTE1 = 'Alte Institutii (I)'), 'Institutie 5', 'I5','1231', '7654', '1 Decembrie 53', 'Alba Iulia', 'https://ro.lipsum.com/', '0740684322', 'activitiorga@gmail.com', '0285369544','J01/2012', 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Observatie alte institutii 1', 0);
	
INSERT INTO NOMENCLATOR_VALUES (ID, NOMENCLATOR_ID, ATTRIBUTE1, ATTRIBUTE2, ATTRIBUTE3, ATTRIBUTE4, ATTRIBUTE5, ATTRIBUTE6,ATTRIBUTE7, ATTRIBUTE8, ATTRIBUTE9, ATTRIBUTE10, ATTRIBUTE11, ATTRIBUTE12, ATTRIBUTE13, ATTRIBUTE14, ATTRIBUTE15, ATTRIBUTE16, ATTRIBUTE17, ATTRIBUTE18, ATTRIBUTE19, ATTRIBUTE20, ATTRIBUTE21, ATTRIBUTE22, ATTRIBUTE23, ATTRIBUTE24, ATTRIBUTE25, DELETED) 
    VALUES (HIBERNATE_SEQUENCE.nextval, (select ID from nomenclator where name='Institutii'), (SELECT ID FROM NOMENCLATOR_VALUES WHERE NOMENCLATOR_ID=(select ID from nomenclator where name='Tip Institutii') and  ATTRIBUTE1 = 'Alte Institutii (I)'), 'Institutie 6', 'I6','43221', '3543543', 'Traian 63', 'Alba Iulia', 'https://ro.lipsum.com/', '0745687654', 'activitiorga@mail.com', '0285363689','J01/2014', 'true', '2017.02.20', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Observatie alte institutii 2', 0);
	
