----script pt adaugare tipuri calendare
INSERT INTO CALENDAR (ID,NAME,DESCRIPTION,COLOR,PERMIT_ALL) VALUES (HIBERNATE_SEQUENCE.NEXTVAL,'Deplasari',null,'#d641f4',0);
INSERT INTO CALENDAR (ID,NAME,DESCRIPTION,COLOR,PERMIT_ALL) VALUES (HIBERNATE_SEQUENCE.NEXTVAL,'Misiuni CMAS',null,'#42b3f4',0);
INSERT INTO CALENDAR (ID,NAME,DESCRIPTION,COLOR,PERMIT_ALL) VALUES (HIBERNATE_SEQUENCE.NEXTVAL,'Aniversari',null,'#41f473',0);
INSERT INTO CALENDAR (ID,NAME,DESCRIPTION,COLOR,PERMIT_ALL) VALUES (HIBERNATE_SEQUENCE.NEXTVAL,'Concedii',null,'#41f473',0);
INSERT INTO CALENDAR (ID,NAME,DESCRIPTION,COLOR,PERMIT_ALL) VALUES (HIBERNATE_SEQUENCE.NEXTVAL,'Personale',null,'#eef441',0);
INSERT INTO CALENDAR (ID,NAME,DESCRIPTION,COLOR,PERMIT_ALL) VALUES (HIBERNATE_SEQUENCE.NEXTVAL,'Sedinte Comisii GL',null,'#42b3f4',0);
INSERT INTO CALENDAR (ID,NAME,DESCRIPTION,COLOR,PERMIT_ALL) VALUES (HIBERNATE_SEQUENCE.NEXTVAL,'Sedinte interne ARB ',null,'#42b3f4',0);
INSERT INTO CALENDAR (ID,NAME,DESCRIPTION,COLOR,PERMIT_ALL) VALUES (HIBERNATE_SEQUENCE.NEXTVAL,'AGA ARB',null,'#f44a41',0);
INSERT INTO CALENDAR (ID,NAME,DESCRIPTION,COLOR,PERMIT_ALL) VALUES (HIBERNATE_SEQUENCE.NEXTVAL,'CD ARB',null,'#f48042',0);
INSERT INTO CALENDAR (ID,NAME,DESCRIPTION,COLOR,PERMIT_ALL) VALUES (HIBERNATE_SEQUENCE.NEXTVAL,'Intalnire PVG ',null,'#f48042',0);
INSERT INTO CALENDAR (ID,NAME,DESCRIPTION,COLOR,PERMIT_ALL) VALUES (HIBERNATE_SEQUENCE.NEXTVAL,'Evenimente/intalniri ',null,'#d641f4',0);
INSERT INTO CALENDAR (ID,NAME,DESCRIPTION,COLOR,PERMIT_ALL) VALUES (HIBERNATE_SEQUENCE.NEXTVAL,'Activitati administrative/mentenanta',null,'#5541f4',0);
INSERT INTO CALENDAR (ID,NAME,DESCRIPTION,COLOR,PERMIT_ALL) VALUES (HIBERNATE_SEQUENCE.NEXTVAL,'Sedinte Parlament',null,'#f44a41',0);
