---drepturi pe calendare florin.ninu
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Aniversari'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'florin.ninu'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Sedinte Parlament'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'florin.ninu'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Activitati administrative/mentenanta'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'florin.ninu'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Evenimente/intalniri'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'florin.ninu'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Intalnire PVG'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'florin.ninu'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='CD ARB'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'florin.ninu'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='AGA ARB'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'florin.ninu'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Sedinte interne ARB'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'florin.ninu'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Sedinte Comisii GL'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'florin.ninu'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Misiuni CMAS'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'florin.ninu'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Deplasari'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'florin.ninu'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Concedii'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'florin.ninu'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
    
---drepturi pe calendare florin.danescu
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Aniversari'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'florin.danescu'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Sedinte Parlament'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'florin.danescu'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Activitati administrative/mentenanta'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'florin.danescu'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Evenimente/intalniri'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'florin.danescu'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Intalnire PVG'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'florin.danescu'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='CD ARB'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'florin.danescu'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='AGA ARB'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'florin.danescu'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Sedinte interne ARB'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'florin.danescu'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Sedinte Comisii GL'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'florin.danescu'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Misiuni CMAS'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'florin.danescu'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Deplasari'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'florin.danescu'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Concedii'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'florin.danescu'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Personale'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'florin.danescu'),1,1,1,'1',HIBERNATE_SEQUENCE.NEXTVAL);    

---drepturi pe calendare rodica.tuchila
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Aniversari'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'rodica.tuchila'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Sedinte Parlament'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'rodica.tuchila'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Activitati administrative/mentenanta'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'rodica.tuchila'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Evenimente/intalniri'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'rodica.tuchila'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Intalnire PVG'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'rodica.tuchila'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='CD ARB'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'rodica.tuchila'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='AGA ARB'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'rodica.tuchila'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Sedinte interne ARB'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'rodica.tuchila'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Sedinte Comisii GL'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'rodica.tuchila'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Misiuni CMAS'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'rodica.tuchila'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Deplasari'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'rodica.tuchila'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Concedii'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'rodica.tuchila'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL); 
 
---drepturi pe calendare cati.ursu
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Aniversari'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'cati.ursu'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Sedinte Parlament'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'cati.ursu'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Activitati administrative/mentenanta'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'cati.ursu'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Evenimente/intalniri'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'cati.ursu'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Intalnire PVG'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'cati.ursu'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='CD ARB'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'cati.ursu'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='AGA ARB'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'cati.ursu'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Sedinte interne ARB'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'cati.ursu'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Sedinte Comisii GL'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'cati.ursu'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Misiuni CMAS'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'cati.ursu'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Deplasari'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'cati.ursu'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Concedii'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'cati.ursu'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL); 

---drepturi pe calendare gabriela.folcut
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Aniversari'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'gabriela.folcut'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Sedinte Parlament'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'gabriela.folcut'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Activitati administrative/mentenanta'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'gabriela.folcut'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Evenimente/intalniri'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'gabriela.folcut'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Intalnire PVG'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'gabriela.folcut'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='CD ARB'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'gabriela.folcut'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='AGA ARB'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'gabriela.folcut'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Sedinte interne ARB'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'gabriela.folcut'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Sedinte Comisii GL'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'gabriela.folcut'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Misiuni CMAS'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'gabriela.folcut'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Deplasari'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'gabriela.folcut'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Concedii'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'gabriela.folcut'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL); 
    
---drepturi pe calendare luminita.malanciuc
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Aniversari'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'luminita.malanciuc'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Sedinte Parlament'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'luminita.malanciuc'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Activitati administrative/mentenanta'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'luminita.malanciuc'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Evenimente/intalniri'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'luminita.malanciuc'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Intalnire PVG'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'luminita.malanciuc'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='CD ARB'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'luminita.malanciuc'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='AGA ARB'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'luminita.malanciuc'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Sedinte interne ARB'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'luminita.malanciuc'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Sedinte Comisii GL'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'luminita.malanciuc'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Misiuni CMAS'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'luminita.malanciuc'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Deplasari'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'luminita.malanciuc'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Concedii'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'luminita.malanciuc'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL); 
 
---drepturi pe calendare constantin.rotaru
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Aniversari'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'constantin.rotaru'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Sedinte Parlament'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'constantin.rotaru'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Activitati administrative/mentenanta'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'constantin.rotaru'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Evenimente/intalniri'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'constantin.rotaru'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Intalnire PVG'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'constantin.rotaru'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='CD ARB'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'constantin.rotaru'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='AGA ARB'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'constantin.rotaru'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Sedinte interne ARB'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'constantin.rotaru'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Sedinte Comisii GL'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'constantin.rotaru'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Misiuni CMAS'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'constantin.rotaru'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Deplasari'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'constantin.rotaru'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Concedii'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'constantin.rotaru'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL); 
  
---drepturi pe calendare tatiana.grafcenco
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Aniversari'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'tatiana.grafcenco'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Sedinte Parlament'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'tatiana.grafcenco'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Activitati administrative/mentenanta'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'tatiana.grafcenco'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Evenimente/intalniri'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'tatiana.grafcenco'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Intalnire PVG'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'tatiana.grafcenco'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='CD ARB'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'tatiana.grafcenco'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='AGA ARB'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'tatiana.grafcenco'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Sedinte interne ARB'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'tatiana.grafcenco'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Sedinte Comisii GL'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'tatiana.grafcenco'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Misiuni CMAS'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'tatiana.grafcenco'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Deplasari'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'tatiana.grafcenco'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Concedii'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'tatiana.grafcenco'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL); 

---drepturi pe calendare cristina.dumitrescu
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Aniversari'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'cristina.dumitrescu'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Sedinte Parlament'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'cristina.dumitrescu'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Activitati administrative/mentenanta'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'cristina.dumitrescu'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Evenimente/intalniri'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'cristina.dumitrescu'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Intalnire PVG'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'cristina.dumitrescu'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='CD ARB'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'cristina.dumitrescu'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='AGA ARB'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'cristina.dumitrescu'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Sedinte interne ARB'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'cristina.dumitrescu'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Sedinte Comisii GL'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'cristina.dumitrescu'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Misiuni CMAS'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'cristina.dumitrescu'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Deplasari'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'cristina.dumitrescu'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Concedii'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'cristina.dumitrescu'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL); 
   
---drepturi pe calendare luminita.soitu
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Aniversari'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'luminita.soitu'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Sedinte Parlament'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'luminita.soitu'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Activitati administrative/mentenanta'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'luminita.soitu'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Evenimente/intalniri'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'luminita.soitu'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Intalnire PVG'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'luminita.soitu'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='CD ARB'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'luminita.soitu'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='AGA ARB'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'luminita.soitu'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Sedinte interne ARB'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'luminita.soitu'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Sedinte Comisii GL'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'luminita.soitu'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Misiuni CMAS'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'luminita.soitu'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Deplasari'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'luminita.soitu'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Concedii'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'luminita.soitu'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL); 
  
---drepturi pe calendare bogdan.martimof
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Aniversari'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'bogdan.martimof'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Sedinte Parlament'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'bogdan.martimof'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Activitati administrative/mentenanta'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'bogdan.martimof'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Evenimente/intalniri'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'bogdan.martimof'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Intalnire PVG'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'bogdan.martimof'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='CD ARB'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'bogdan.martimof'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='AGA ARB'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'bogdan.martimof'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Sedinte interne ARB'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'bogdan.martimof'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Sedinte Comisii GL'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'bogdan.martimof'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Misiuni CMAS'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'bogdan.martimof'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Deplasari'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'bogdan.martimof'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Concedii'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'bogdan.martimof'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL); 
 
---drepturi pe calendare stefan.dina
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Aniversari'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'stefan.dina'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Sedinte Parlament'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'stefan.dina'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Activitati administrative/mentenanta'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'stefan.dina'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Evenimente/intalniri'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'stefan.dina'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Intalnire PVG'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'stefan.dina'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='CD ARB'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'stefan.dina'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='AGA ARB'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'stefan.dina'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Sedinte interne ARB'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'stefan.dina'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Sedinte Comisii GL'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'stefan.dina'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Misiuni CMAS'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'stefan.dina'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Deplasari'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'stefan.dina'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Concedii'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'stefan.dina'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL); 
  
---drepturi pe calendare lina.visan
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Aniversari'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'lina.visan'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Sedinte Parlament'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'lina.visan'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Activitati administrative/mentenanta'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'lina.visan'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Evenimente/intalniri'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'lina.visan'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Intalnire PVG'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'lina.visan'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='CD ARB'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'lina.visan'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='AGA ARB'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'lina.visan'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Sedinte interne ARB'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'lina.visan'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Sedinte Comisii GL'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'lina.visan'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Misiuni CMAS'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'lina.visan'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Deplasari'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'lina.visan'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Concedii'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'lina.visan'),1,0,0,'0',HIBERNATE_SEQUENCE.NEXTVAL); 
  
---drepturi pe calendare adriana.tudor
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Aniversari'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'adriana.tudor'),1,1,1,'1',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Sedinte Parlament'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'adriana.tudor'),1,1,1,'1',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Activitati administrative/mentenanta'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'adriana.tudor'),1,1,1,'1',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Evenimente/intalniri'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'adriana.tudor'),1,1,1,'1',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Intalnire PVG'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'adriana.tudor'),1,1,1,'1',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='CD ARB'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'adriana.tudor'),1,1,1,'1',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='AGA ARB'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'adriana.tudor'),1,1,1,'1',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Sedinte interne ARB'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'adriana.tudor'),1,1,1,'1',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Sedinte Comisii GL'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'adriana.tudor'),1,1,1,'1',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Misiuni CMAS'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'adriana.tudor'),1,1,1,'1',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Deplasari'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'adriana.tudor'),1,1,1,'1',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Concedii'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'adriana.tudor'),1,1,1,'1',HIBERNATE_SEQUENCE.NEXTVAL); 

---drepturi pe calendare andreea.rosu
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Aniversari'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'andreea.rosu'),1,1,1,'1',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Sedinte Parlament'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'andreea.rosu'),1,1,1,'1',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Activitati administrative/mentenanta'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'andreea.rosu'),1,1,1,'1',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Evenimente/intalniri'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'andreea.rosu'),1,1,1,'1',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Intalnire PVG'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'andreea.rosu'),1,1,1,'1',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='CD ARB'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'andreea.rosu'),1,1,1,'1',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='AGA ARB'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'andreea.rosu'),1,1,1,'1',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Sedinte interne ARB'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'andreea.rosu'),1,1,1,'1',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Sedinte Comisii GL'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'andreea.rosu'),1,1,1,'1',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Misiuni CMAS'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'andreea.rosu'),1,1,1,'1',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Deplasari'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'andreea.rosu'),1,1,1,'1',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Concedii'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'andreea.rosu'),1,1,1,'1',HIBERNATE_SEQUENCE.NEXTVAL); 
 
---drepturi pe calendare liviu.chitu
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Aniversari'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'liviu.chitu'),1,1,1,'1',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Sedinte Parlament'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'liviu.chitu'),1,1,1,'1',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Activitati administrative/mentenanta'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'liviu.chitu'),1,1,1,'1',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Evenimente/intalniri'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'liviu.chitu'),1,1,1,'1',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Intalnire PVG'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'liviu.chitu'),1,1,1,'1',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='CD ARB'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'liviu.chitu'),1,1,1,'1',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='AGA ARB'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'liviu.chitu'),1,1,1,'1',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Sedinte interne ARB'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'liviu.chitu'),1,1,1,'1',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Sedinte Comisii GL'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'liviu.chitu'),1,1,1,'1',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Misiuni CMAS'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'liviu.chitu'),1,1,1,'1',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Deplasari'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'liviu.chitu'),1,1,1,'1',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Concedii'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'liviu.chitu'),1,1,1,'1',HIBERNATE_SEQUENCE.NEXTVAL); 

---drepturi pe calendare sorina.sirbu
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Aniversari'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'sorina.sirbu'),1,1,1,'1',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Sedinte Parlament'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'sorina.sirbu'),1,1,1,'1',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Activitati administrative/mentenanta'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'sorina.sirbu'),1,1,1,'1',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Evenimente/intalniri'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'sorina.sirbu'),1,1,1,'1',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Intalnire PVG'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'sorina.sirbu'),1,1,1,'1',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='CD ARB'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'sorina.sirbu'),1,1,1,'1',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='AGA ARB'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'sorina.sirbu'),1,1,1,'1',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Sedinte interne ARB'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'sorina.sirbu'),1,1,1,'1',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Sedinte Comisii GL'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'sorina.sirbu'),1,1,1,'1',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Misiuni CMAS'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'sorina.sirbu'),1,1,1,'1',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Deplasari'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'sorina.sirbu'),1,1,1,'1',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Concedii'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'sorina.sirbu'),1,1,1,'1',HIBERNATE_SEQUENCE.NEXTVAL); 
 
---drepturi pe calendare vlad.barabas
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Aniversari'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'vlad.barabas'),1,1,1,'1',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Sedinte Parlament'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'vlad.barabas'),1,1,1,'1',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Activitati administrative/mentenanta'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'vlad.barabas'),1,1,1,'1',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Evenimente/intalniri'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'vlad.barabas'),1,1,1,'1',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Intalnire PVG'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'vlad.barabas'),1,1,1,'1',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='CD ARB'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'vlad.barabas'),1,1,1,'1',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='AGA ARB'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'vlad.barabas'),1,1,1,'1',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Sedinte interne ARB'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'vlad.barabas'),1,1,1,'1',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Sedinte Comisii GL'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'vlad.barabas'),1,1,1,'1',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Misiuni CMAS'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'vlad.barabas'),1,1,1,'1',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Deplasari'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'vlad.barabas'),1,1,1,'1',HIBERNATE_SEQUENCE.NEXTVAL);
INSERT INTO CLOUDFLOW_TEST.CALENDAR_USER_RIGHTS (CALENDAR_ID,USER_RIGHT_ORG_ENTITY_ID,VIEW_RIGHT,ADD_RIGHT,EDIT_RIGHT,DELETE_RIGHT,ID) 
	VALUES ((SELECT ID FROM CALENDAR WHERE NAME ='Concedii'),(SELECT ORG_ENTITY_ID FROM EDOCUSER WHERE USERNAME = 'vlad.barabas'),1,1,1,'1',HIBERNATE_SEQUENCE.NEXTVAL); 
    
    
    
    
    