export enum AdminPermissionEnum {
	
	MANAGE_ORGANIZATIONAL_STRUCTURE = "admin.MANAGE_ORGANIZATIONAL_STRUCTURE",
	MANAGE_GROUPS = "admin.MANAGE_GROUPS",
	MANAGE_ROLES_AND_PERMISSIONS = "admin.MANAGE_ROLES_AND_PERMISSIONS",
	MANAGE_DOCUMENT_TYPES = "admin.MANAGE_DOCUMENT_TYPES",
	MANAGE_MIME_TYPES = "admin.MANAGE_MIME_TYPES",
	MANAGE_WORKFLOWS = "admin.MANAGE_WORKFLOWS",
	MANAGE_CALENDARS = "admin.MANAGE_CALENDARS",
	MANAGE_NOMENCLATORS = "admin.MANAGE_NOMENCLATORS",
	MANAGE_REPLACEMENT_PROFILES = "admin.MANAGE_REPLACEMENT_PROFILES",
	MANAGE_PARAMETERS = "admin.MANAGE_PARAMETERS",
	EDIT_REGISTRU_INTRARI_IESIRI_ELEVATED = "admin.EDIT_REGISTRU_INTRARI_IESIRI_ELEVATED",
	EDIT_TASK_EVENT_DESCRIPTIONS = "admin.EDIT_TASK_EVENT_DESCRIPTIONS",
	EDIT_IMPORTANCE_RANK_DESCRIPTION = "admin.EDIT_IMPORTANCE_RANK_DESCRIPTION"
	
}