export enum ClientPermissionEnum {

	ACCESS_DASHBOARD = "client.ACCESS_DASHBOARD",
	MANAGE_DOCUMENTS = "client.MANAGE_DOCUMENTS",
	ADMIN_UPDATE_DOCUMENT = "client.ADMIN_UPDATE_DOCUMENT",
	MANAGE_PROJECTS = "client.MANAGE_PROJECTS",
	ACCESS_REPORTS = "client.ACCESS_REPORTS",
	VIEW_CALEDAR = "client.VIEW_CALENDAR",
	EDIT_CALEDAR = "client.EDIT_CALENDAR",
	VIEW_NOMENCLATORS = "client.VIEW_NOMENCLATORS",
	EDIT_NOMENCLATORS = "client.EDIT_NOMENCLATORS",
	VIEW_REGISTRU_DOCUMENTE_JUSTIFICATIVE_PLATI = "client.VIEW_REGISTRU_DOCUMENTE_JUSTIFICATIVE_PLATI",
	EDIT_REGISTRU_DOCUMENTE_JUSTIFICATIVE_PLATI = "client.EDIT_REGISTRU_DOCUMENTE_JUSTIFICATIVE_PLATI",
	VIEW_COMISII_GL = "client.VIEW_COMISII_GL",
	EDIT_COMISII_GL = "client.EDIT_COMISII_GL",
	VIEW_REGISTRU_INTRARI_IESIRI = "client.VIEW_REGISTRU_INTRARI_IESIRI",
	EDIT_REGISTRU_INTRARI_IESIRI = "client.EDIT_REGISTRU_INTRARI_IESIRI",
	VIEW_DEPLASARI_DECONTURI = "client.VIEW_DEPLASARI_DECONTURI",
	EDIT_DEPLASARI_DECONTURI = "client.EDIT_DEPLASARI_DECONTURI",
	VIEW_ALTE_DECONTURI = "client.VIEW_ALTE_DECONTURI",
	EDIT_ALTE_DECONTURI = "client.EDIT_ALTE_DECONTURI"
}