export enum RoleEnum {
	ADMIN = "ADMIN",
	SECRETARIAT = "SECRETARIAT",
	CONSILIER = "CONSILIER",
	RESPONSABIL_PROIECT = "RESPONSABIL_PROIECT",
	DIRECTOR = "DIRECTOR",
	MANAGER = "MANAGER",
	LOGISTICA = "LOGISTICA",
	HR = "HR",
	BOM = "BOM",
	LEGAL = "LEGAL"
}