export enum TransitionNotificationModelType {

	ASSIGNED_ENTITY = "ASSIGNED_ENTITY",
	INITIATOR = "INITIATOR",
	HIERARCHICAL_SUPERIOR_OF_INITIATOR = "HIERARCHICAL_SUPERIOR_OF_INITIATOR",
	MANUALLY_CHOSEN_ENTITIES = "MANUALLY_CHOSEN_ENTITIES",
	METADATA = "METADATA",
	HIERARCHICAL_SUPERIOR_OF_USER_METADATA = "HIERARCHICAL_SUPERIOR_OF_USER_METADATA",
}