-- 'UAT Local - Admin' care e posibil sa fie 'ADMIN'
WITH groupRow AS (
	INSERT INTO ORGANIZATIONENTITY (ORG_ENTITY_ID) VALUES (nextval('HIBERNATE_SEQUENCE'))
	RETURNING ORG_ENTITY_ID
) INSERT INTO EDOCGROUP (
	ORG_ENTITY_ID, 
	NAME
) VALUES (
	(select ORG_ENTITY_ID from groupRow), 
	'UAT Local - Admin'
);
INSERT INTO GROUP_USER (
	GROUP_ID,
	USER_ID
) SELECT
	(select ORG_ENTITY_ID from EDOCGROUP where NAME = 'UAT Local - Admin'),
	ORG_ENTITY_ID
FROM EDOCUSER WHERE USERNAME IN ('vlad.barabas');


WITH groupRow AS (
	INSERT INTO ORGANIZATIONENTITY (ORG_ENTITY_ID) VALUES (nextval('HIBERNATE_SEQUENCE'))
	RETURNING ORG_ENTITY_ID
) INSERT INTO EDOCGROUP (
	ORG_ENTITY_ID, 
	NAME
) VALUES (
	(select ORG_ENTITY_ID from groupRow), 
	'Logistica'
);
INSERT INTO GROUP_USER (
	GROUP_ID,
	USER_ID
) SELECT
	(select ORG_ENTITY_ID from EDOCGROUP where NAME = 'Logistica'),
	ORG_ENTITY_ID
FROM EDOCUSER WHERE USERNAME IN ('cati.ursu','gabriela.folcut','florin.ninu','vlad.barabas');


WITH groupRow AS (
	INSERT INTO ORGANIZATIONENTITY (ORG_ENTITY_ID) VALUES (nextval('HIBERNATE_SEQUENCE'))
	RETURNING ORG_ENTITY_ID
) INSERT INTO EDOCGROUP (
	ORG_ENTITY_ID, 
	NAME
) VALUES (
	(select ORG_ENTITY_ID from groupRow), 
	'ARB CD'
);
INSERT INTO GROUP_USER (
	GROUP_ID,
	USER_ID
) SELECT
	(select ORG_ENTITY_ID from EDOCGROUP where NAME = 'ARB CD'),
	ORG_ENTITY_ID
FROM EDOCUSER WHERE USERNAME IN ('florin.danescu', 'rodica.tuchila','cati.ursu','gabriela.folcut','luminita.malanciuc','constantin.rotaru','tatiana.grafcenco','cristina.dumitrescu','luminita.soitu','bogdan.martimof','stefan.dina');

WITH groupRow AS (
	INSERT INTO ORGANIZATIONENTITY (ORG_ENTITY_ID) VALUES (nextval('HIBERNATE_SEQUENCE'))
	RETURNING ORG_ENTITY_ID
) INSERT INTO EDOCGROUP (
	ORG_ENTITY_ID, 
	NAME
) VALUES (
	(select ORG_ENTITY_ID from groupRow), 
	'BOM'
);
INSERT INTO GROUP_USER (
	GROUP_ID,
	USER_ID
) SELECT
	(select ORG_ENTITY_ID from EDOCGROUP where NAME = 'BOM'),
	ORG_ENTITY_ID
FROM EDOCUSER WHERE USERNAME IN ('andreea.rosu', 'sorina.sirbu');


WITH groupRow AS (
	INSERT INTO ORGANIZATIONENTITY (ORG_ENTITY_ID) VALUES (nextval('HIBERNATE_SEQUENCE'))
	RETURNING ORG_ENTITY_ID
) INSERT INTO EDOCGROUP (
	ORG_ENTITY_ID, 
	NAME
) VALUES (
	(select ORG_ENTITY_ID from groupRow), 
	'Director DEPR'
);
INSERT INTO GROUP_USER (
	GROUP_ID,
	USER_ID
) SELECT
	(select ORG_ENTITY_ID from EDOCGROUP where NAME = 'Director DEPR'),
	ORG_ENTITY_ID
FROM EDOCUSER WHERE USERNAME IN ('cati.ursu');

WITH groupRow AS (
	INSERT INTO ORGANIZATIONENTITY (ORG_ENTITY_ID) VALUES (nextval('HIBERNATE_SEQUENCE'))
	RETURNING ORG_ENTITY_ID
) INSERT INTO EDOCGROUP (
	ORG_ENTITY_ID, 
	NAME
) VALUES (
	(select ORG_ENTITY_ID from groupRow), 
	'PE'
);
INSERT INTO GROUP_USER (
	GROUP_ID,
	USER_ID
) SELECT
	(select ORG_ENTITY_ID from EDOCGROUP where NAME = 'PE'),
	ORG_ENTITY_ID
FROM EDOCUSER WHERE USERNAME IN ('florin.danescu');

WITH groupRow AS (
	INSERT INTO ORGANIZATIONENTITY (ORG_ENTITY_ID) VALUES (nextval('HIBERNATE_SEQUENCE'))
	RETURNING ORG_ENTITY_ID
) INSERT INTO EDOCGROUP (
	ORG_ENTITY_ID, 
	NAME
) VALUES (
	(select ORG_ENTITY_ID from groupRow), 
	'PE BOM'
);
INSERT INTO GROUP_USER (
	GROUP_ID,
	USER_ID
) SELECT
	(select ORG_ENTITY_ID from EDOCGROUP where NAME = 'PE BOM'),
	ORG_ENTITY_ID
FROM EDOCUSER WHERE USERNAME IN ('florin.danescu', 'sorina.sirbu');


WITH groupRow AS (
	INSERT INTO ORGANIZATIONENTITY (ORG_ENTITY_ID) VALUES (nextval('HIBERNATE_SEQUENCE'))
	RETURNING ORG_ENTITY_ID
) INSERT INTO EDOCGROUP (
	ORG_ENTITY_ID, 
	NAME
) VALUES (
	(select ORG_ENTITY_ID from groupRow), 
	'Responsabili GL Comisie'
);
INSERT INTO GROUP_USER (
	GROUP_ID,
	USER_ID
) SELECT
	(select ORG_ENTITY_ID from EDOCGROUP where NAME = 'Responsabili GL Comisie'),
	ORG_ENTITY_ID
FROM EDOCUSER WHERE USERNAME IN ('rodica.tuchila', 'cati.ursu','gabriela.folcut','luminita.malanciuc','constantin.rotaru','tatiana.grafcenco','cristina.dumitrescu','luminita.soitu','bogdan.martimof','stefan.dina','adriana.tudor','andreea.rosu','vlad.barabas');

WITH groupRow AS (
	INSERT INTO ORGANIZATIONENTITY (ORG_ENTITY_ID) VALUES (nextval('HIBERNATE_SEQUENCE'))
	RETURNING ORG_ENTITY_ID
) INSERT INTO EDOCGROUP (
	ORG_ENTITY_ID, 
	NAME
) VALUES (
	(select ORG_ENTITY_ID from groupRow), 
	'Secretariat'
);
INSERT INTO GROUP_USER (
	GROUP_ID,
	USER_ID
) SELECT
	(select ORG_ENTITY_ID from EDOCGROUP where NAME = 'Secretariat'),
	ORG_ENTITY_ID
FROM EDOCUSER WHERE USERNAME IN ('sorina.sirbu','adriana.tudor','andreea.rosu','liviu.chitu');