package ro.cloudSoft.cloudDoc.services.report;

import java.util.List;

import ro.cloudSoft.cloudDoc.core.AppException;
import ro.cloudSoft.cloudDoc.domain.security.SecurityManager;
import ro.cloudSoft.cloudDoc.presentation.client.shared.model.report.ActiuniOrganizateDeArbReportFilterModel;
import ro.cloudSoft.cloudDoc.presentation.client.shared.model.report.ActiuniOrganizateDeArbReportModel;
import ro.cloudSoft.cloudDoc.presentation.client.shared.model.report.ActiuniPeProiectReportFilterModel;
import ro.cloudSoft.cloudDoc.presentation.client.shared.model.report.ActiuniPeProiectReportModel;
import ro.cloudSoft.cloudDoc.presentation.client.shared.model.report.AderareOioroReportFilterModel;
import ro.cloudSoft.cloudDoc.presentation.client.shared.model.report.AderareOioroReportRowModel;
import ro.cloudSoft.cloudDoc.presentation.client.shared.model.report.CentralizatorPrezentaPerioadaReportFilterModel;
import ro.cloudSoft.cloudDoc.presentation.client.shared.model.report.CentralizatorPrezentaPerioadaReportModel;
import ro.cloudSoft.cloudDoc.presentation.client.shared.model.report.CereriConcediuReportBundle;
import ro.cloudSoft.cloudDoc.presentation.client.shared.model.report.CereriConcediuReportFilterModel;
import ro.cloudSoft.cloudDoc.presentation.client.shared.model.report.CereriConcediuReportModel;
import ro.cloudSoft.cloudDoc.presentation.client.shared.model.report.DashboardProiecteFilterBundle;
import ro.cloudSoft.cloudDoc.presentation.client.shared.model.report.DashboardProiecteFilterModel;
import ro.cloudSoft.cloudDoc.presentation.client.shared.model.report.DashboardProiecteRowReportModel;
import ro.cloudSoft.cloudDoc.presentation.client.shared.model.report.DecontCheltuieliAlteDeconturiReportFilterModel;
import ro.cloudSoft.cloudDoc.presentation.client.shared.model.report.DecontCheltuieliAlteDeconturiReportModel;
import ro.cloudSoft.cloudDoc.presentation.client.shared.model.report.DeplasariDeconturiReportBundleModel;
import ro.cloudSoft.cloudDoc.presentation.client.shared.model.report.DeplasariDeconturiReportFilterModel;
import ro.cloudSoft.cloudDoc.presentation.client.shared.model.report.DeplasariDeconturiReportRowModel;
import ro.cloudSoft.cloudDoc.presentation.client.shared.model.report.DocumentIdentifierModel;
import ro.cloudSoft.cloudDoc.presentation.client.shared.model.report.ListaProiectelorCareAuVizatActiunileLuniiReportFilterModel;
import ro.cloudSoft.cloudDoc.presentation.client.shared.model.report.ListaProiectelorCareAuVizatActiunileLuniiReportModel;
import ro.cloudSoft.cloudDoc.presentation.client.shared.model.report.MembriiAfiliatiReportFilterModel;
import ro.cloudSoft.cloudDoc.presentation.client.shared.model.report.MembriiAfiliatiReportModel;
import ro.cloudSoft.cloudDoc.presentation.client.shared.model.report.NivelReprezentareComisiiReportFilterModel;
import ro.cloudSoft.cloudDoc.presentation.client.shared.model.report.NivelReprezentareComisiiReportModel;
import ro.cloudSoft.cloudDoc.presentation.client.shared.model.report.NotaGeneralaPeMembriiArbReportFilterModel;
import ro.cloudSoft.cloudDoc.presentation.client.shared.model.report.NotaGeneralaPeMembriiArbReportModel;
import ro.cloudSoft.cloudDoc.presentation.client.shared.model.report.NotaGeneralaReportFilterModel;
import ro.cloudSoft.cloudDoc.presentation.client.shared.model.report.NotaGeneralaReportRowModel;
import ro.cloudSoft.cloudDoc.presentation.client.shared.model.report.NoteBanciReportFilterModel;
import ro.cloudSoft.cloudDoc.presentation.client.shared.model.report.NoteBanciReportModel;
import ro.cloudSoft.cloudDoc.presentation.client.shared.model.report.NumarParticipantiSedinteComisieGlReportBundle;
import ro.cloudSoft.cloudDoc.presentation.client.shared.model.report.NumarParticipantiSedinteComisieGlReportFilterModel;
import ro.cloudSoft.cloudDoc.presentation.client.shared.model.report.NumarParticipantiSedinteComisieGlReportModel;
import ro.cloudSoft.cloudDoc.presentation.client.shared.model.report.NumarSedinteCdPvgSiParticipantiReportFilterModel;
import ro.cloudSoft.cloudDoc.presentation.client.shared.model.report.NumarSedinteCdPvgSiParticipantiReportModel;
import ro.cloudSoft.cloudDoc.presentation.client.shared.model.report.NumarSedinteComisieGlReportFilterModel;
import ro.cloudSoft.cloudDoc.presentation.client.shared.model.report.NumarSedinteComisieGlReportModel;
import ro.cloudSoft.cloudDoc.presentation.client.shared.model.report.ParticipareReprezentantiArbLaActiuniInAfaraAsociatieiReportFilterModel;
import ro.cloudSoft.cloudDoc.presentation.client.shared.model.report.ParticipareReprezentantiArbLaActiuniInAfaraAsociatieiReportModel;
import ro.cloudSoft.cloudDoc.presentation.client.shared.model.report.PrezentaAgaFilterModel;
import ro.cloudSoft.cloudDoc.presentation.client.shared.model.report.PrezentaAgaReportModel;
import ro.cloudSoft.cloudDoc.presentation.client.shared.model.report.PrezentaComisiiGlInIntervalReportBundle;
import ro.cloudSoft.cloudDoc.presentation.client.shared.model.report.PrezentaComisiiGlInIntervalReportFilterModel;
import ro.cloudSoft.cloudDoc.presentation.client.shared.model.report.PrezentaComisiiGlInIntervalReportModel;
import ro.cloudSoft.cloudDoc.presentation.client.shared.model.report.PrezentaReprezentivitateReportFilterModel;
import ro.cloudSoft.cloudDoc.presentation.client.shared.model.report.PrezentaReprezentivitateReportModel;
import ro.cloudSoft.cloudDoc.presentation.client.shared.model.report.PrezentaSedintaCdPvgInvitatiARBReportFilterModel;
import ro.cloudSoft.cloudDoc.presentation.client.shared.model.report.PrezentaSedintaCdPvgInvitatiARBReportModel;
import ro.cloudSoft.cloudDoc.presentation.client.shared.model.report.PrezentaSedintaCdPvgInvitatiExterniFilterModel;
import ro.cloudSoft.cloudDoc.presentation.client.shared.model.report.PrezentaSedintaCdPvgMembriiReportFilterModel;
import ro.cloudSoft.cloudDoc.presentation.client.shared.model.report.PrezentaSedintaCdPvgMembriiReportModel;
import ro.cloudSoft.cloudDoc.presentation.client.shared.model.report.PrezentaSedinteCdPvgInvitatiExterniReportModel;
import ro.cloudSoft.cloudDoc.presentation.client.shared.model.report.RaspunsuriBanciReportBundleModel;
import ro.cloudSoft.cloudDoc.presentation.client.shared.model.report.RaspunsuriBanciReportFilterModel;
import ro.cloudSoft.cloudDoc.presentation.client.shared.model.report.RaspunsuriBanciReportRowModel;
import ro.cloudSoft.cloudDoc.presentation.client.shared.model.report.ReprezentantiBancaPerFunctieSiComisieReportFilterModel;
import ro.cloudSoft.cloudDoc.presentation.client.shared.model.report.ReprezentantiBancaPerFunctieSiComisieReportModel;
import ro.cloudSoft.cloudDoc.presentation.client.shared.model.report.TaskuriCumulateReportFilterModel;
import ro.cloudSoft.cloudDoc.presentation.client.shared.model.report.TaskuriCumulateReportModel;
import ro.cloudSoft.cloudDoc.presentation.client.shared.model.report.cheltuieliArbSiReprezentantArb.CheltuieliArbSiReprezentantArbReportFilterModel;
import ro.cloudSoft.cloudDoc.presentation.client.shared.model.report.cheltuieliArbSiReprezentantArb.CheltuieliArbSiReprezentantArbReportModel;
import ro.cloudSoft.cloudDoc.presentation.client.shared.model.report.deplasareDecont.CheltuieliReprezentantArbReportFilterModel;
import ro.cloudSoft.cloudDoc.presentation.client.shared.model.report.deplasareDecont.CheltuieliReprezentantArbReportModel;
import ro.cloudSoft.cloudDoc.presentation.client.shared.model.report.documenteTrimiseDeArb.DocumenteTrimiseDeArbReportFilterModel;
import ro.cloudSoft.cloudDoc.presentation.client.shared.model.report.documenteTrimiseDeArb.DocumenteTrimiseDeArbReportModel;
import ro.cloudSoft.cloudDoc.presentation.client.shared.model.report.participariLaEvenimente.ParticipariEvenimenteReportFilterModel;
import ro.cloudSoft.cloudDoc.presentation.client.shared.model.report.participariLaEvenimente.ParticipariEvenimenteReportRowModel;

public interface ReportService {

	NumarSedinteCdPvgSiParticipantiReportModel getNumarSedinteCdPvgSiParticipantiReport(NumarSedinteCdPvgSiParticipantiReportFilterModel filter) throws AppException;

	List<ParticipariEvenimenteReportRowModel> getParticipariEvenimenteReport(ParticipariEvenimenteReportFilterModel filter) throws AppException;
	
	PrezentaSedinteCdPvgInvitatiExterniReportModel getPrezentaSedinteCdPvgInvitatiExterniReport(PrezentaSedintaCdPvgInvitatiExterniFilterModel filter) throws AppException;

	List<AderareOioroReportRowModel> getAderareOioroReport(AderareOioroReportFilterModel filter) throws AppException;
	
	PrezentaSedintaCdPvgMembriiReportModel getPrezentaSedintaCdPvgMembriiReport(PrezentaSedintaCdPvgMembriiReportFilterModel filter) throws AppException;

	CheltuieliReprezentantArbReportModel getDeplasariDeconturiCheltuieliReprezentantArb(CheltuieliReprezentantArbReportFilterModel filter) throws AppException;

	CheltuieliArbSiReprezentantArbReportModel getCheltuieliArbSiReprezentantArbReport(CheltuieliArbSiReprezentantArbReportFilterModel filter) throws AppException;

	PrezentaComisiiGlInIntervalReportBundle getPrezentaComisiiGlInIntervalReportBundle( DocumentIdentifierModel document, SecurityManager userSecurity) throws AppException;
	
	PrezentaComisiiGlInIntervalReportModel getPrezentaComisiiGlInIntervalReport(PrezentaComisiiGlInIntervalReportFilterModel filter) throws AppException;

	PrezentaSedintaCdPvgInvitatiARBReportModel getPrezentaSedinteCdPvgInvitatiArbReport(PrezentaSedintaCdPvgInvitatiARBReportFilterModel filter, ro.cloudSoft.cloudDoc.domain.security.SecurityManager securityManager) throws AppException;
	
	List<DocumenteTrimiseDeArbReportModel> getDocumenteTrimiseDeArbReport(DocumenteTrimiseDeArbReportFilterModel filter) throws AppException;

	NumarParticipantiSedinteComisieGlReportModel getNumarParticipantiSedinteComisieGlReport(NumarParticipantiSedinteComisieGlReportFilterModel filter) throws AppException;

	ActiuniPeProiectReportModel getActiuniPeProiectReport(ActiuniPeProiectReportFilterModel filter) throws AppException;

	NumarParticipantiSedinteComisieGlReportBundle getNumarParticipantiSedinteComisieGlReportBundle() throws AppException;

	ActiuniOrganizateDeArbReportModel getActiuniOrganizateDeArbReport(ActiuniOrganizateDeArbReportFilterModel filter, SecurityManager userSecurity) throws AppException;

	List<DashboardProiecteRowReportModel> getDashboardProiecteReport(DashboardProiecteFilterModel filter) throws AppException;

	DashboardProiecteFilterBundle getDashboardProiecteFilterBundle();
	
	DecontCheltuieliAlteDeconturiReportModel getAlteDeconturiCheltuieliReprezentantArbReport(DecontCheltuieliAlteDeconturiReportFilterModel filter) throws AppException;
	
	ParticipareReprezentantiArbLaActiuniInAfaraAsociatieiReportModel getParticipareReprezentantiArbLaActiuniInAfaraAsociatieiReport(ParticipareReprezentantiArbLaActiuniInAfaraAsociatieiReportFilterModel filter, SecurityManager userSecurity) throws AppException;

	List<ListaProiectelorCareAuVizatActiunileLuniiReportModel> getListaProiectelorCareAuVizatActiunileLuniiReport(ListaProiectelorCareAuVizatActiunileLuniiReportFilterModel filter) throws AppException;

	PrezentaAgaReportModel getPrezentaAgaReport(PrezentaAgaFilterModel filter) throws AppException;

	NumarSedinteComisieGlReportModel getNumarSedinteComisieGlReport(NumarSedinteComisieGlReportFilterModel filter) throws AppException;

	MembriiAfiliatiReportModel getMembriiAfiliatiReport(MembriiAfiliatiReportFilterModel filter) throws AppException;
	
	TaskuriCumulateReportModel getTaskuriCumulateReport(TaskuriCumulateReportFilterModel filter) throws AppException;

	List<DeplasariDeconturiReportRowModel> getDeplasariDeconturiReport(DeplasariDeconturiReportFilterModel filter) throws AppException;

	DeplasariDeconturiReportBundleModel getDeplasariDeconturiReportBundle();
	
	CereriConcediuReportBundle getCereriConcediuReportBundle();
	
	CereriConcediuReportModel getCereriConcediuReport(CereriConcediuReportFilterModel filter) throws AppException;
	
	PrezentaReprezentivitateReportModel getPrezentaComisiiArbReprezentativitate(PrezentaReprezentivitateReportFilterModel filter) throws AppException;

	List<RaspunsuriBanciReportRowModel> getRaspunsuriBanciReport(RaspunsuriBanciReportFilterModel filter);

	RaspunsuriBanciReportBundleModel getRaspunsuriBanciReportBundle();
	
	ReprezentantiBancaPerFunctieSiComisieReportModel getReprezentantiBancaPerFunctieSiComisieReport(ReprezentantiBancaPerFunctieSiComisieReportFilterModel filter) throws AppException;

	CentralizatorPrezentaPerioadaReportModel getCentralizatorPrezentaPerioadaReport(CentralizatorPrezentaPerioadaReportFilterModel filter) throws AppException;
	
	NotaGeneralaPeMembriiArbReportModel getNotaGeneralaPeMembriiArbReport(NotaGeneralaPeMembriiArbReportFilterModel filter) throws AppException;

	List<NotaGeneralaReportRowModel> getNotaGeneralaReport(NotaGeneralaReportFilterModel filter) throws AppException;

	NivelReprezentareComisiiReportModel getNivelReprezentareComisiiReport(NivelReprezentareComisiiReportFilterModel filter) throws AppException;

	NoteBanciReportModel getNoteBanciReport(NoteBanciReportFilterModel filter) throws AppException;

}
