export enum AdminPermissionEnum {
	
	MANAGE_PARAMETERS = "admin.MANAGE_PARAMETERS",
	MANAGE_DRIVERS = "admin.MANAGE_DRIVERS",
	MANAGE_DISPATCHERS = "admin.MANAGE_DISPATCHERS",
	MANAGE_CARS = "admin.MANAGE_CARS"
	
}